BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '5min';

CREATE TABLE IF NOT EXISTS public.agent_sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  collaboration_mode text NOT NULL CHECK (collaboration_mode IN ('direct', 'assist', 'takeover')),
  messages jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(messages) = 'array'),
  summary jsonb NOT NULL CHECK (jsonb_typeof(summary) = 'object'),
  tool_results jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(tool_results) = 'array'),
  knowledge_refs jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(knowledge_refs) = 'array'),
  token_budget jsonb NOT NULL CHECK (jsonb_typeof(token_budget) = 'object'),
  confirmations jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(confirmations) = 'array'),
  checkpoints jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(checkpoints) = 'array'),
  last_heartbeat_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS agent_sessions_user_updated_idx
  ON public.agent_sessions(user_id, updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.agent_context_snapshots (
  snapshot_id text PRIMARY KEY,
  session_id text NOT NULL REFERENCES public.agent_sessions(id) ON DELETE CASCADE,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  snapshot_data jsonb NOT NULL CHECK (jsonb_typeof(snapshot_data) = 'object'),
  captured_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, sequence)
);

CREATE INDEX IF NOT EXISTS agent_context_snapshots_session_sequence_idx
  ON public.agent_context_snapshots(session_id, sequence DESC);

COMMIT;
