// apps/web/src/services/llm/wuyinCatalog.ts
// 职责：提供速创 API 的共享模型目录定义、内置 Fallback 目录以及“只填 Key”的一键接入配置构造逻辑。

import { buildCanonicalApiRecordId } from '../auth/keyManagerCanonicalIds.ts';
import { WUYIN_PRESET_LOGO_URL } from '../auth/keyManagerProviderPresets.ts';
import type { WuyinCatalogItemDto } from '@kk/shared';

export type WuyinModelKind = WuyinCatalogItemDto['kind'];
export type WuyinExecutionMode = WuyinCatalogItemDto['executionMode'];
export type WuyinSubmitContentType = WuyinCatalogItemDto['submitContentType'];
export type WuyinCatalogItem = WuyinCatalogItemDto;

export const WUYIN_DEFAULT_BASE_URL = 'https://api.wuyinkeji.com';
export const WUYIN_ASYNC_DETAIL_PATH = '/api/async/detail';
export const WUYIN_IMAGE_MODEL_PRIORITY = [
  'image_nanoBanana2',
  'image_nanoBanana_pro',
  'image_nanoBanana',
  'image_gpt',
];

function readWuyinCatalogModelId(item: { id?: string; modelId?: string; endpointPath?: string }): string {
  const explicit = String(item.id || item.modelId || '').trim();
  if (explicit) return explicit;

  const path = String(item.endpointPath || '').trim();
  const match = path.match(/\/api\/async\/([^/?#]+)$/i);
  return match ? decodeURIComponent(match[1]) : '';
}

function getWuyinCatalogPriority(item: { id?: string; modelId?: string; endpointPath?: string }): number {
  const modelId = readWuyinCatalogModelId(item);
  const index = WUYIN_IMAGE_MODEL_PRIORITY.findIndex((candidate) => candidate.toLowerCase() === modelId.toLowerCase());
  return index >= 0 ? index : WUYIN_IMAGE_MODEL_PRIORITY.length + 1000;
}

export function sortWuyinCatalogByDefaultPriority<T extends { id?: string; modelId?: string; endpointPath?: string }>(items: T[]): T[] {
  return items
    .map((item, index) => ({ item, index }))
    .sort((left, right) => {
      const rankDiff = getWuyinCatalogPriority(left.item) - getWuyinCatalogPriority(right.item);
      return rankDiff || left.index - right.index;
    })
    .map(({ item }) => item);
}

export const WUYIN_DEFAULT_CATALOG: WuyinCatalogItem[] = [
  {
    id: 'image_gpt',
    name: 'GPT-Image-2',
    displayName: 'GPT-Image-2',
    categoryName: '图片模型',
    kind: 'image',
    executionMode: 'async-detail',
    endpointPath: '/api/async/image_gpt',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.1,
    priceText: '0.1元/张',
    priceUnit: '张',
    aliases: ['gpt-image-2', 'gpt image 2', 'image_gpt'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'image_nanoBanana2',
    name: 'NanoBanana2',
    displayName: 'NanoBanana2',
    categoryName: '图片模型',
    kind: 'image',
    executionMode: 'async-detail',
    endpointPath: '/api/async/image_nanoBanana2',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.1,
    priceText: '0.1元/张',
    priceUnit: '张',
    aliases: ['nanobanana2', 'nano-banana-2', 'nano banana 2', 'gemini-3.1-flash-image-preview', 'gemini-3.1-flash-image', 'image_nanoBanana2'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'image_grok_imagine',
    name: 'grok_imagine',
    displayName: 'grok_imagine',
    categoryName: '图片模型',
    kind: 'image',
    executionMode: 'async-detail',
    endpointPath: '/api/async/image_grok_imagine',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.1,
    priceText: '0.1元/张',
    priceUnit: '张',
    aliases: ['grok_imagine', 'grok imagine', 'image_grok_imagine'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'image_nanoBanana_pro',
    name: 'NanoBanana_pro',
    displayName: 'NanoBanana_pro',
    categoryName: '图片模型',
    kind: 'image',
    executionMode: 'async-detail',
    endpointPath: '/api/async/image_nanoBanana_pro',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.3,
    priceText: '0.3元/张',
    priceUnit: '张',
    aliases: ['nanobanana_pro', 'nanobanana-pro', 'nano-banana-pro', 'nano banana pro', 'gemini-3-pro-image-preview', 'image_nanoBanana_pro'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'image_nanoBanana',
    name: 'NanoBanana',
    displayName: 'NanoBanana',
    categoryName: '图片模型',
    kind: 'image',
    executionMode: 'async-detail',
    endpointPath: '/api/async/image_nanoBanana',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.1,
    priceText: '0.1元/张',
    priceUnit: '张',
    aliases: ['nanobanana', 'nano-banana', 'nano banana', 'gemini-2.5-flash-image', 'image_nanoBanana'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'image_wan2.6',
    name: 'Wan2.6',
    displayName: 'Wan2.6',
    categoryName: '图片模型',
    kind: 'image',
    executionMode: 'async-detail',
    endpointPath: '/api/async/image_wan2.6',
    method: 'POST',
    contentType: 'application/x-www-form-urlencoded',
    submitContentType: 'application/x-www-form-urlencoded',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.2,
    priceText: '0.2元/张',
    priceUnit: '张',
    aliases: ['wan2.6', 'wan26', 'wan image', 'image_wan2.6'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'video_google_omni',
    name: 'google_omni',
    displayName: 'google_omni',
    categoryName: '视频模型',
    kind: 'video',
    executionMode: 'async-detail',
    endpointPath: '/api/async/video_google_omni',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.1,
    priceText: '0.1元/秒',
    priceUnit: '秒',
    aliases: ['google_omni', 'google omni', 'video_google_omni'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'video_vidu',
    name: 'video_vidu',
    displayName: 'video_vidu',
    categoryName: '视频模型',
    kind: 'video',
    executionMode: 'async-detail',
    endpointPath: '/api/async/video_vidu',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 1.0,
    priceText: '1.0元/秒',
    priceUnit: '秒',
    aliases: ['vidu', 'video_vidu'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'video_omni',
    name: 'video_omni',
    displayName: 'video_omni',
    categoryName: '视频模型',
    kind: 'video',
    executionMode: 'async-detail',
    endpointPath: '/api/async/video_omni',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 1.0,
    priceText: '1.0元/秒',
    priceUnit: '秒',
    aliases: ['video_omni', 'omni video'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'video_digital_humans',
    name: 'Digital_Humans',
    displayName: 'Digital_Humans',
    categoryName: '视频模型',
    kind: 'video',
    executionMode: 'async-detail',
    endpointPath: '/api/async/video_digital_humans',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.02,
    priceText: '0.02元/秒',
    priceUnit: '秒',
    aliases: ['digital_humans', 'digital humans', 'video_digital_humans'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'video_package',
    name: 'Package_1.0',
    displayName: 'Package_1.0',
    categoryName: '视频模型',
    kind: 'video',
    executionMode: 'async-detail',
    endpointPath: '/api/async/video_package',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.02,
    priceText: '0.02元/秒',
    priceUnit: '秒',
    aliases: ['package_1.0', 'video_package'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'video_veo3.1_fast',
    name: 'veo3.1_fast',
    displayName: 'veo3.1_fast',
    categoryName: '视频模型',
    kind: 'video',
    executionMode: 'async-detail',
    endpointPath: '/api/async/video_veo3.1_fast',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.05,
    priceText: '0.05元/秒',
    priceUnit: '秒',
    aliases: ['veo3.1_fast', 'veo 3.1 fast', 'video_veo3.1_fast'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'video_grok_imagine',
    name: 'grok_imagine',
    displayName: 'grok_imagine',
    categoryName: '视频模型',
    kind: 'video',
    executionMode: 'async-detail',
    endpointPath: '/api/async/video_grok_imagine',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.05,
    priceText: '0.05元/秒',
    priceUnit: '秒',
    aliases: ['grok_imagine', 'grok imagine video', 'video_grok_imagine'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'video_wan2.6',
    name: 'Wan2.6',
    displayName: 'Wan2.6',
    categoryName: '视频模型',
    kind: 'video',
    executionMode: 'async-detail',
    endpointPath: '/api/async/video_wan2.6',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.8,
    priceText: '0.8元/秒',
    priceUnit: '秒',
    aliases: ['wan2.6', 'wan26', 'wan video', 'video_wan2.6'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'chat_index',
    name: 'ChatAPI',
    displayName: 'ChatAPI',
    categoryName: '对话模型',
    kind: 'chat',
    executionMode: 'sync',
    endpointPath: '/api/chat/index',
    method: 'POST',
    contentType: 'application/x-www-form-urlencoded',
    submitContentType: 'application/x-www-form-urlencoded',
    price: 0,
    priceText: '免费',
    priceUnit: 'token',
    aliases: ['chatapi', 'chat_index', 'api/chat/index'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'audio_tts',
    name: '语音合成',
    displayName: '语音合成',
    categoryName: '音频模型',
    kind: 'audio',
    executionMode: 'async-detail',
    endpointPath: '/api/async/audio_tts',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/async/detail',
    detailStatusMode: 'wuyin-async',
    price: 0.0006,
    priceText: '0.0006元/字符',
    priceUnit: '字符',
    aliases: ['audio_tts', 'tts'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'voice_composite',
    name: '语音合成（同步）',
    displayName: '语音合成（同步）',
    categoryName: '音频模型',
    kind: 'audio',
    executionMode: 'sync',
    endpointPath: '/api/voice/composite',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    price: 0.0006,
    priceText: '0.0006元/字符',
    priceUnit: '字符',
    aliases: ['voice_composite', 'voice composite'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'voice_clone',
    name: '语音克隆（同步）',
    displayName: '语音克隆（同步）',
    categoryName: '音频模型',
    kind: 'audio',
    executionMode: 'sync',
    endpointPath: '/api/voice/clone',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    price: 6,
    priceText: '6元/次',
    priceUnit: '次',
    aliases: ['voice_clone', 'voice clone'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'sora2-new',
    name: 'sora2-new',
    displayName: 'sora2-new',
    categoryName: '备用接口',
    kind: 'video',
    executionMode: 'sora2-special',
    endpointPath: '/api/sora2-new/submit',
    method: 'POST',
    contentType: 'application/json',
    submitContentType: 'application/json',
    detailPath: '/api/sora2/detail',
    detailStatusMode: 'sora2',
    price: 1.2,
    priceText: '1.2元/次',
    priceUnit: '次',
    aliases: ['sora2-new', 'sora2'],
    enabled: true,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
  {
    id: 'img_split',
    name: '智能拼图',
    displayName: '智能拼图',
    categoryName: '备用接口',
    kind: 'utility',
    executionMode: 'sync',
    endpointPath: '/api/img/split',
    method: 'POST',
    contentType: 'application/x-www-form-urlencoded',
    submitContentType: 'application/x-www-form-urlencoded',
    price: 0.03,
    priceText: '0.03元/次',
    priceUnit: '次',
    aliases: ['img_split', 'split'],
    enabled: false,
    lastCrawledAt: '2026-06-02T19:07:23Z',
  },
];

export function buildWuyinOneKeyProvider(
  apiKey: string,
  catalog: WuyinCatalogItem[] = WUYIN_DEFAULT_CATALOG,
  options?: {
    providerId?: string;
    keySlotId?: string;
    existingProviderIds?: string[];
    existingSlotIds?: string[];
  },
) {
  const key = String(apiKey || '').trim();
  if (!key) throw new Error('请填写速创 API 密钥');

  const enabledCatalog = sortWuyinCatalogByDefaultPriority(
    catalog.filter(item => item.enabled)
  );
  const supportedModels = enabledCatalog.map(item => item.id);
  const providerId = buildCanonicalApiRecordId(
    {
      id: options?.providerId,
      name: '速创 API',
      provider: 'Wuyin',
      baseUrl: WUYIN_DEFAULT_BASE_URL,
    },
    options?.existingProviderIds || [],
  );
  const keySlotId = buildCanonicalApiRecordId(
    {
      id: options?.keySlotId,
      name: '速创 API',
      provider: 'Wuyin',
      baseUrl: WUYIN_DEFAULT_BASE_URL,
    },
    options?.existingSlotIds || [],
  );
  const providerLegacyIds = options?.providerId && options.providerId.toLowerCase() !== providerId.toLowerCase()
    ? [options.providerId]
    : undefined;
  const keySlotLegacyIds = options?.keySlotId && options.keySlotId.toLowerCase() !== keySlotId.toLowerCase()
    ? [options.keySlotId]
    : undefined;

  const provider = {
    id: providerId,
    legacyIds: providerLegacyIds,
    name: '速创 API',
    provider: 'Wuyin',
    baseUrl: WUYIN_DEFAULT_BASE_URL,
    apiKey: key,
    format: 'openai' as const,
    icon: WUYIN_PRESET_LOGO_URL,
    authMethod: 'header' as const,
    headerName: 'Authorization',
    authorizationValueFormat: 'raw',
    compatibilityMode: 'standard' as const,
    models: enabledCatalog.map(item => item.id), // 保存为模型ID的数组
    pricingSnapshot: {
      fetchedAt: Date.now(),
      source: 'wuyin-catalog',
      rows: catalog as any[],
      updatedAt: new Date().toISOString(),
    },
  };

  const keySlot = {
    id: keySlotId,
    legacyIds: keySlotLegacyIds,
    name: '速创 API',
    provider: 'Wuyin',
    type: 'third-party' as const,
    key,
    baseUrl: WUYIN_DEFAULT_BASE_URL,
    format: 'openai' as const,
    authMethod: 'header' as const,
    headerName: 'Authorization',
    compatibilityMode: 'standard' as const,
    supportedModels,
    status: 'valid' as const,
    pricingSnapshot: provider.pricingSnapshot,
  };

  return { provider, keySlot };
}
