// 中文注释：平台无关的设计令牌，用于在不同端统一主题色、布局、动态与配色逻辑
export const UI_SYSTEM_TOKENS = {
  color: {
    canvas: '#000000',
    page: '#171717',
    panel: 'oklch(0.235 0 0)',
    control: 'oklch(0.2603 0 0)',
    hover: 'rgba(255, 255, 255, 0.08)',
    border: 'rgba(255, 255, 255, 0.06)',
    textPrimary: 'oklch(0.97 0 0)',
    textSecondary: 'oklch(0.708 0 0)',
    textMuted: 'oklch(0.556 0 0)',
    textDisabled: 'oklch(0.439 0 0)',
    actionPrimary: 'oklch(0.5926 0.2236 258.42)',
    content: 'oklch(0.235 0 0)',
    accent: 'oklch(0.5926 0.2236 258.42)',
    support: 'oklch(0.7 0.12 205)',
    success: 'oklch(0.72 0.17 150)',
    warning: 'oklch(0.78 0.16 78)',
    danger: 'oklch(0.68 0.2 25)',
  },
  breakpoints: {
    phoneSmall: 375,
    phoneStandard: 430,
    tablet: 768,
    desktop: 1024,
    desktopWide: 1280,
    desktopLarge: 1440,
  },
  spacing: {
    1: "var(--kk-space-1)",
    2: "var(--kk-space-2)",
    3: "var(--kk-space-3)",
    4: "var(--kk-space-4)",
    5: "var(--kk-space-5)",
    6: "var(--kk-space-6)",
    8: "var(--kk-space-8)",
    10: "var(--kk-space-10)",
    12: "var(--kk-space-12)",
  },
  layout: {
    mobilePageMargin: "8px",
    tabletPageMargin: "24px",
    desktopPageMargin: "32px",
    contentMaxWidth: "1200px",
    contentWideMaxWidth: "1440px",
    touchTargetMin: "44px",
    desktopControlHeight: "36px",
    mobileControlHeight: "44px",
  },
  typography: {
    fontFamily: 'Inter, sans-serif',
    display: '24px',
    title: '16px',
    body: '14px',
    button: '12px',
    caption: '11px',
    bodyMobile: "16px",
    bodyDesktop: "14px",
    weightRegular: 400,
    weightMedium: 500,
    weightSemibold: 600,
    lineHeightBody: "1.5",
    lineHeightTight: "1.2",
  },
  icon: {
    feature: '20px',
    button: '16px',
    assist: '13px',
  },
  radius: {
    button: '7px',
    control: '8px',
    panel: '14px',
    composer: '20px',
    pill: '9999px',
  },
  motion: {
    durationFast: "100ms",
    durationStandard: "125ms",
    durationPanel: "160ms",
    easeStandard: "var(--kk-motion-ease-standard)",
  },
  canvas: {
    card: {
      surface: 'oklch(0.22 0 0)',
      border: 'rgba(255, 255, 255, 0.07)',
      selectedRing: 'color-mix(in oklch, oklch(0.5926 0.2236 258.42) 26%, transparent)',
    },
    edge: {
      idle: 'rgba(255, 255, 255, 0.18)',
      disabled: 'rgba(255, 255, 255, 0.08)',
      selected: 'oklch(0.5926 0.2236 258.42)',
    },
  },
  glass: {
    surface: "var(--kk-glass-surface-bg)",
    border: "var(--kk-glass-surface-border)",
    blur: "var(--kk-ui-glass-blur)",
    opacity: "var(--kk-ui-glass-opacity)",
  },
} as const;

export const TOKENS = {
  colors: {
    background: UI_SYSTEM_TOKENS.color.canvas,
    surface: UI_SYSTEM_TOKENS.color.panel,
    surfaceSolid: UI_SYSTEM_TOKENS.color.panel,
    surfaceGlass: UI_SYSTEM_TOKENS.color.panel,
    surfaceGlassBorder: UI_SYSTEM_TOKENS.color.border,
    textPrimary: UI_SYSTEM_TOKENS.color.textPrimary,
    textSecondary: UI_SYSTEM_TOKENS.color.textSecondary,
    textTertiary: UI_SYSTEM_TOKENS.color.textMuted,
    borderSubtle: UI_SYSTEM_TOKENS.color.border,
    brandPrimary: UI_SYSTEM_TOKENS.color.actionPrimary,
    brandCoral: "var(--kk-color-brand-coral)",
    accentIndigo: UI_SYSTEM_TOKENS.color.actionPrimary,
    accentEmerald: "#10B981",
    accentAmber: "#F59E0B",
    glowAccent: "color-mix(in oklch, var(--kk-morphic-action) 30%, transparent)",
  },
  radius: {
    sm: UI_SYSTEM_TOKENS.radius.button,
    md: UI_SYSTEM_TOKENS.radius.control,
    lg: UI_SYSTEM_TOKENS.radius.panel,
    xl: UI_SYSTEM_TOKENS.radius.composer,
    full: UI_SYSTEM_TOKENS.radius.pill,
  },
  shadows: {
    surface: "var(--kk-shadow-surface)",
    floating: "var(--kk-shadow-floating)",
    primaryAction: "var(--kk-shadow-primary-action)",
    cardSelected: "0 0 0 2px #6366F1, 0 10px 25px -5px rgba(99, 102, 241, 0.4)",
    glow: "0 0 20px rgba(99, 102, 241, 0.35)",
  },
  typography: {
    fontFamily: "Inter, Roboto, sans-serif",
    displayFontFamily: "Inter, sans-serif",
  },
  uiSystem: UI_SYSTEM_TOKENS,
};

export type ThemeTokens = typeof TOKENS;
