import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import test from 'node:test';
import { readSource } from '../support/workspacePaths.js';

const MIGRATION_PATH = 'infrastructure/database/migrations/021_agent_sessions.sql';

function assertBefore(source: string, before: string, after: string, label: string) {
  const beforeIndex = source.indexOf(before);
  const afterIndex = source.indexOf(after);
  assert.ok(beforeIndex >= 0, `${label}: missing ${before}`);
  assert.ok(afterIndex >= 0, `${label}: missing ${after}`);
  assert.ok(beforeIndex < afterIndex, `${label}: expected ordered migration application`);
}

test('migration 021 adds owner-scoped Sessions and metadata-only Context Snapshots', () => {
  assert.equal(existsSync(MIGRATION_PATH), true);
  const migration = readSource(MIGRATION_PATH);

  assert.match(migration, /^BEGIN;/);
  assert.match(migration, /SET LOCAL lock_timeout = '10s'/);
  assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.agent_sessions/);
  assert.match(migration, /user_id text NOT NULL/);
  assert.match(migration, /messages jsonb NOT NULL/);
  assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.agent_context_snapshots/);
  assert.match(migration, /session_id text NOT NULL REFERENCES public\.agent_sessions\(id\) ON DELETE CASCADE/);
  assert.match(migration, /snapshot_id text PRIMARY KEY/);
  assert.match(migration, /sequence bigint GENERATED BY DEFAULT AS IDENTITY/);
  assert.doesNotMatch(migration, /input_text|attachment_data|user_message|tool_payload/i);
  assert.match(migration, /COMMIT;\s*$/);
});

test('bootstrap and database entrypoints apply migration 021 after Run events', () => {
  const bootstrap = readSource('scripts/ops/postgres/bootstrap-kk-vps.sql');
  const linuxBootstrap = readSource('scripts/ops/vps/bootstrap-kk-vps.sh');
  const windowsSetup = readSource('scripts/ops/setup/setup-database.bat');
  const runtimeImport = readSource('scripts/ops/postgres/import-runtime-into-vps.sh');
  const deploy = readSource('scripts/ops/vps/deploy-kk-vps.sh');

  assert.match(bootstrap, /CREATE TABLE IF NOT EXISTS public\.agent_sessions/);
  assert.match(bootstrap, /CREATE TABLE IF NOT EXISTS public\.agent_context_snapshots/);
  for (const [label, source] of [
    ['Linux bootstrap', linuxBootstrap],
    ['Windows setup', windowsSetup],
    ['runtime import', runtimeImport],
    ['deploy', deploy],
  ] as const) {
    assertBefore(source, '020_agent_run_events.sql', '021_agent_sessions.sql', label);
  }
  assert.match(deploy, /\('agent_sessions'\)/);
  assert.match(deploy, /\('agent_context_snapshots'\)/);
  assert.match(deploy, /agent_sessions schema is missing or invalid/);
});

test('full API catalog documents authoritative Run, Session, event, and Context paths', () => {
  const apiSpec = readSource('docs/specs/openapi-full.yaml');

  assert.match(apiSpec, /^  \/api\/ai-assistant\/sessions:$/m);
  assert.match(apiSpec, /^  \/api\/ai-assistant\/sessions\/\{sessionId\}:$/m);
  assert.match(apiSpec, /^  \/api\/ai-assistant\/sessions\/\{sessionId\}\/context-snapshots:$/m);
  assert.match(apiSpec, /^  \/api\/ai-assistant\/sessions\/\{sessionId\}\/context-snapshots\/latest:$/m);
  assert.match(apiSpec, /^  \/api\/ai-assistant\/runs\/\{runId\}:$/m);
  assert.match(apiSpec, /^  \/api\/ai-assistant\/runs\/\{runId\}\/events:$/m);
});
